### ISSUE TITLE
How to scale horizontally

### ISSUE THREAD

**Issue by kkweon** [rodaine/grpc-chat#3]
Hi thank you for the awesome repo.
I know this repo is not dealing with scalability but i want to hear how you would do it if you want to scale to multiple nodes?
Thanks

**Comment by rodaine** [comment]
Thanks for taking a look! 

In order to scale this horizontally you'd need to move the message management to somewhere with shared state. Keeping with the ephemeral behavior of this implementation, I'd recommend a pub-sub system like [NATS](https://docs.nats.io/nats-concepts/pubsub) that can handle this very effectively. So when clients connect, subscribe them to a topic on NATS, then as they publish messages, write those messages into the topic and they'll be propagated to all connected subscribers. 

If you need some sort of persistence or want to share the historical state, You'll either need a database or a tool like Kafka that has journaling. NATS does support some QoS, but I haven't had a chance to play with it.

**Comment by kkweon** [comment]
Thank you for your answer!
